### ISSUE TITLE
Sometimes avatar shop won't be replaced with "catalog" when "original topbar" is selected

### ISSUE THREAD

**Issue by Tyyde** [WingedDash/DashBlox#7] opened 2021-11-01 07:17 UTC
![01 11 2021_17 16 20_REC](https://user-images.githubusercontent.com/93511610/139635379-f93c0d75-2693-4a9c-8173-a8d94aab1f4f.png)

No, this is not a problem with another Chrome extension, this is the only extension I have that changes "avatar shop" back to "catalog".

**Comment by WingedDash** [comment] 2021-11-03 14:35
This is in fact a problem caused by another extension, there are multiple reasons that other extensions could be causing the issue.

DashBlox modifies the vanilla text of the Roblox site, and if another extension changes anything within the top bar It can cause the setting to stop working.

**Comment by WingedDash** [comment] 2021-11-03 14:41
Try disabling certain extensions / extension settings and let me know if it's causing this issue and I might issue a fix for it.

**Comment by WingedDash** [comment] 2021-12-10 01:10
Hello, unless you have further information about this, I’ll close this issue for now.

**Closed by WingedDash** 2021-12-10 01:10 UTC
Labels: bug, alternate extension
